#!/usr/bin/env python3
"""Generate the one-file Arcade Road Trip static app."""

from __future__ import annotations

import argparse
import base64
import html
import json
from pathlib import Path

from export_static_data import DEFAULT_OUTPUT_DIR, connect as export_connect, load_location_games, load_route_locations, write_parquet
from generate_dashboard import build_dashboard_data, connect as dashboard_connect


DEFAULT_DB = Path("arcade_roadtrip.duckdb")
DEFAULT_OUTPUT = Path("static/arcade_road_trip.html")


def js_json(value: object) -> str:
    return json.dumps(value, ensure_ascii=True, separators=(",", ":")).replace("</", "<\\/")


def ensure_parquet(db_path: Path, output_dir: Path) -> dict[str, int]:
    output_dir.mkdir(parents=True, exist_ok=True)
    with export_connect(db_path) as conn:
        route_locations = load_route_locations(conn)
        location_games = load_location_games(conn)
    write_parquet(route_locations, output_dir / "route_locations.parquet")
    write_parquet(location_games, output_dir / "location_games.parquet")
    return {"route_locations": len(route_locations), "location_games": len(location_games)}


def embedded_parquet(data_dir: Path, counts: dict[str, int]) -> dict[str, object]:
    return {
        "route_locations": base64.b64encode((data_dir / "route_locations.parquet").read_bytes()).decode("ascii"),
        "location_games": base64.b64encode((data_dir / "location_games.parquet").read_bytes()).decode("ascii"),
        "manifest": {"counts": counts},
    }


def build_html(dashboard: dict[str, object], parquet: dict[str, object]) -> str:
    dashboard_payload = js_json(dashboard)
    parquet_payload = js_json(parquet)
    generated = html.escape(str(dashboard["generated_at"]))
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Arcade Road Trip Atlas</title>
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Bungee&family=Chakra+Petch:wght@400;500;600;700&family=Monoton&family=Press+Start+2P&display=swap" />
  <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" />
  <style>
    :root {{
      --night:#06020f; --panel:rgba(22,10,48,.72); --ink:#f3ecff; --muted:#b3a4d6; --line:rgba(160,120,255,.28);
      --teal:#25e6ff; --gold:#ffd23f; --coral:#ff5e3a; --rare:#ff3dd6; --blue:#25e6ff;
      --pink:#ff2d95; --cyan:#25e6ff; --violet:#8b5cff; --lime:#59ff9c;
      --paper:var(--panel); --wash:var(--night);
      --font-neon:'Monoton',cursive; --font-display:'Bungee',system-ui,sans-serif;
      --font-body:'Chakra Petch',system-ui,-apple-system,'Segoe UI',sans-serif; --font-pixel:'Press Start 2P',monospace;
    }}
    * {{ box-sizing:border-box; }}
    html,body {{ height:100%; min-height:100%; }}
    body {{ margin:0; font-family:var(--font-body); color:var(--ink); background:radial-gradient(1100px 620px at 12% -8%,rgba(255,45,149,.22),transparent 60%),radial-gradient(1000px 560px at 92% -4%,rgba(37,230,255,.16),transparent 58%),linear-gradient(180deg,#0a0420 0%,#06020f 46%,#0b0322 100%); background-attachment:fixed; }}
    body::before {{ content:""; position:fixed; inset:0; z-index:-2; pointer-events:none; opacity:.5; background-image:linear-gradient(rgba(139,92,255,.16) 1px,transparent 1px),linear-gradient(90deg,rgba(139,92,255,.16) 1px,transparent 1px); background-size:46px 46px; -webkit-mask-image:radial-gradient(circle at 50% 118%,#000 0%,rgba(0,0,0,.5) 42%,transparent 74%); mask-image:radial-gradient(circle at 50% 118%,#000 0%,rgba(0,0,0,.5) 42%,transparent 74%); }}
    body::after {{ content:""; position:fixed; inset:0; z-index:-1; pointer-events:none; opacity:.15; background:repeating-linear-gradient(to bottom,rgba(0,0,0,0) 0 2px,rgba(0,0,0,.7) 2px 3px); }}
    body.planner-active {{ overflow:hidden; }}
    button,input {{ font:inherit; }} button {{ cursor:pointer; }}
    p {{ line-height:1.55; }}
    ::-webkit-scrollbar {{ width:11px; height:11px; }} ::-webkit-scrollbar-track {{ background:rgba(8,3,20,.6); }} ::-webkit-scrollbar-thumb {{ background:linear-gradient(180deg,var(--violet),var(--pink)); border-radius:999px; border:2px solid rgba(8,3,20,.6); }} ::-webkit-scrollbar-thumb:hover {{ background:linear-gradient(180deg,var(--pink),var(--cyan)); }}
    header {{ position:sticky; top:0; z-index:20; color:var(--ink); background:linear-gradient(180deg,rgba(10,4,32,.95),rgba(10,4,32,.80)); backdrop-filter:blur(12px) saturate(140%); border-bottom:1px solid rgba(255,45,149,.45); box-shadow:0 8px 34px rgba(0,0,0,.6),0 0 26px rgba(255,45,149,.16); }}
    .topbar {{ display:flex; align-items:center; justify-content:space-between; gap:14px; padding:14px min(5vw,48px); }}
    .brand {{ font-family:var(--font-neon); font-weight:400; font-size:clamp(19px,2.5vw,29px); line-height:1.05; letter-spacing:.03em; color:#fff; text-shadow:0 0 6px #ff2d95,0 0 16px #ff2d95,0 0 32px rgba(255,45,149,.7),0 0 46px rgba(37,230,255,.35); }}
    .brand-sub {{ display:block; margin-top:7px; font-family:var(--font-body); font-size:10px; font-weight:600; letter-spacing:.40em; text-transform:uppercase; color:var(--cyan); text-shadow:0 0 10px rgba(37,230,255,.7); }}
    .tabs {{ display:flex; flex-wrap:wrap; gap:8px; }}
    .tab {{ font-family:var(--font-display); font-size:12px; letter-spacing:.03em; text-transform:uppercase; border:1px solid rgba(37,230,255,.4); color:#dff7ff; background:linear-gradient(180deg,rgba(37,230,255,.12),rgba(37,230,255,.03)); border-radius:10px; padding:9px 14px; box-shadow:inset 0 0 12px rgba(37,230,255,.12); transition:transform .16s,box-shadow .16s,color .16s,border-color .16s; }}
    .tab:hover {{ border-color:var(--cyan); color:#fff; transform:translateY(-1px); box-shadow:0 0 12px rgba(37,230,255,.5),inset 0 0 14px rgba(37,230,255,.2); }}
    .tab.active {{ color:#20002f; border-color:transparent; background:linear-gradient(180deg,#ff6ecb,#ff2d95 58%,#f81f8d); text-shadow:0 1px 0 rgba(255,255,255,.35); box-shadow:0 0 14px rgba(255,45,149,.85),0 0 34px rgba(255,45,149,.45),inset 0 1px 0 rgba(255,255,255,.5); }}
    .roadline {{ position:absolute; left:0; right:0; bottom:0; height:4px; overflow:hidden; pointer-events:none; background:linear-gradient(90deg,rgba(255,45,149,.12),rgba(37,230,255,.22),rgba(255,45,149,.12)); }}
    .roadline::before {{ content:""; position:absolute; inset:0; background:repeating-linear-gradient(90deg,var(--gold) 0 26px,transparent 26px 56px); filter:drop-shadow(0 0 6px rgba(255,210,63,.9)); animation:roadmove 1.2s linear infinite; }}
    @keyframes roadmove {{ to {{ transform:translateX(-56px); }} }}
    .hero {{ padding:20px min(5vw,48px) 28px; display:grid; grid-template-columns:minmax(280px,1fr) minmax(320px,.8fr); gap:22px; align-items:end; }}
    h1 {{ margin:0 0 12px; font-family:var(--font-display); font-weight:400; font-size:clamp(30px,5vw,60px); line-height:1.03; text-transform:uppercase; letter-spacing:.01em; background:linear-gradient(180deg,#fff 0%,#ffd9f2 28%,#ff2d95 62%,#8b5cff 100%); -webkit-background-clip:text; background-clip:text; color:transparent; -webkit-text-fill-color:transparent; filter:drop-shadow(0 0 12px rgba(255,45,149,.5)) drop-shadow(0 0 26px rgba(139,92,255,.32)); }}
    .lede {{ margin:0; color:#dccff8; font-size:16px; line-height:1.5; max-width:760px; text-shadow:0 1px 10px rgba(0,0,0,.55); }}
    .stat-grid {{ display:grid; grid-template-columns:repeat(2,minmax(0,1fr)); gap:10px; }}
    .stat {{ position:relative; overflow:hidden; border:1px solid rgba(37,230,255,.32); background:linear-gradient(180deg,rgba(37,230,255,.10),rgba(20,8,44,.55)); border-radius:12px; padding:13px 14px; box-shadow:inset 0 0 22px rgba(37,230,255,.08),0 6px 18px rgba(0,0,0,.4); }}
    .stat::after {{ content:""; position:absolute; left:0; right:0; top:0; height:2px; background:linear-gradient(90deg,transparent,var(--cyan),transparent); opacity:.85; }}
    .stat b {{ display:block; font-family:var(--font-pixel); font-size:clamp(15px,2.2vw,22px); line-height:1.15; color:#fff; text-shadow:0 0 8px rgba(37,230,255,.9),0 0 20px rgba(37,230,255,.45); }}
    .stat span {{ display:block; margin-top:9px; font-size:10.5px; letter-spacing:.07em; text-transform:uppercase; color:#b9a9e6; }}
    main {{ padding:22px min(5vw,48px) 42px; position:relative; z-index:1; }}
    .view {{ display:none; }} .view.active {{ display:block; animation:viewIn .35s ease; }}
    @keyframes viewIn {{ from {{ opacity:0; transform:translateY(8px); }} }}
    .section-head {{ display:flex; justify-content:space-between; align-items:end; gap:14px; margin:0 0 12px; }}
    h2 {{ font-family:var(--font-display); font-weight:400; font-size:clamp(17px,2.1vw,23px); margin:0; text-transform:uppercase; letter-spacing:.02em; color:#fff; text-shadow:0 0 8px rgba(255,45,149,.55),0 0 20px rgba(255,45,149,.28); }}
    .note,.small {{ color:var(--muted); }} .note {{ margin:5px 0 0; font-size:13px; line-height:1.45; }}
    .panel {{ background:var(--panel); border:1px solid var(--line); border-radius:14px; overflow:hidden; backdrop-filter:blur(8px) saturate(130%); box-shadow:0 12px 34px rgba(0,0,0,.5),0 0 24px rgba(139,92,255,.10),inset 0 0 0 1px rgba(255,255,255,.03); }}
    .panel-pad {{ padding:16px; }} section {{ margin-top:24px; }}
    #hotspot-map {{ height:min(68vh,650px); min-height:430px; background:#0b0620; }}
    .grid-2 {{ display:grid; grid-template-columns:minmax(0,1fr) minmax(0,1fr); gap:18px; align-items:stretch; }} .grid-2 > * {{ min-width:0; }}
    .table-wrap {{ max-height:560px; overflow:auto; }} table {{ width:100%; border-collapse:collapse; font-size:13px; }}
    th,td {{ padding:10px 11px; border-bottom:1px solid rgba(139,92,255,.16); text-align:right; vertical-align:top; }} th:first-child,td:first-child {{ text-align:left; }}
    th {{ position:sticky; top:0; z-index:1; background:linear-gradient(180deg,#1c1040,#150b2e); color:var(--cyan); font-family:var(--font-display); font-weight:400; font-size:11px; letter-spacing:.04em; text-transform:uppercase; cursor:pointer; text-shadow:0 0 8px rgba(37,230,255,.5); }}
    tbody tr {{ transition:background .15s; }} tbody tr:hover {{ background:rgba(255,45,149,.08); }}
    td.name {{ font-weight:700; color:#fff; }}
    .arcade-link {{ color:var(--cyan); text-decoration:none; border-bottom:1px solid rgba(37,230,255,.4); text-shadow:0 0 8px rgba(37,230,255,.3); }} .arcade-link:hover {{ color:#fff; border-bottom-color:#fff; text-shadow:0 0 12px rgba(37,230,255,.9); }}
    .sorter {{ display:inline-flex; gap:6px; flex-wrap:wrap; }} .sorter button {{ font-family:var(--font-display); font-size:11px; letter-spacing:.03em; text-transform:uppercase; border:1px solid var(--line); background:rgba(20,8,44,.6); color:#d7c9ff; border-radius:999px; padding:7px 12px; transition:.16s; }} .sorter button:hover {{ border-color:var(--pink); color:#fff; box-shadow:0 0 10px rgba(255,45,149,.45); }} .sorter button.active {{ background:linear-gradient(180deg,#ff6ecb,#ff2d95); color:#20002f; border-color:transparent; box-shadow:0 0 12px rgba(255,45,149,.6); }}
    .bar {{ display:grid; grid-template-columns:1fr auto; gap:8px; align-items:center; }} .bar span:first-child {{ height:9px; border-radius:999px; min-width:2px; background:linear-gradient(90deg,var(--cyan),var(--violet) 46%,var(--pink)); box-shadow:0 0 10px rgba(255,45,149,.45),0 0 14px rgba(37,230,255,.3); }} .bar b {{ color:#fff; font-weight:700; }} .bar-cell {{ min-width:130px; }} .rare {{ color:var(--rare); font-weight:800; text-shadow:0 0 10px rgba(255,61,214,.55); }}
    #machine-distribution {{ width:100%; height:560px; display:block; }}
    .planner-shell {{ display:grid; grid-template-columns:minmax(430px,.9fr) minmax(480px,1.1fr); height:calc(100dvh - var(--topbar-height, 57px)); min-height:0; overflow:hidden; margin:-22px calc(-1 * min(5vw,48px)) -42px; }}
    .planner-side {{ min-height:0; overflow:hidden; display:flex; flex-direction:column; background:linear-gradient(180deg,rgba(16,7,36,.94),rgba(10,4,26,.94)); border-right:1px solid var(--line); backdrop-filter:blur(6px); }}
    .controls {{ padding:14px 16px 10px; border-bottom:1px solid rgba(139,92,255,.2); }} label {{ display:block; font-size:11px; font-weight:700; letter-spacing:.08em; text-transform:uppercase; color:var(--cyan); margin-bottom:5px; text-shadow:0 0 8px rgba(37,230,255,.3); }} input {{ width:100%; padding:9px 10px; color:#fff; background:rgba(8,3,20,.75); border:1px solid var(--line); border-radius:8px; }} input:focus {{ outline:none; border-color:var(--cyan); box-shadow:0 0 0 1px rgba(37,230,255,.5),0 0 14px rgba(37,230,255,.3); }} input::placeholder {{ color:#7f70a8; }}
    .trip-grid,.action-row {{ display:grid; grid-template-columns:1fr 1fr; gap:8px; align-items:end; }} .action-row {{ grid-template-columns:minmax(140px,1fr) 150px; margin-top:10px; }} .action-row button {{ border:0; border-radius:9px; padding:11px; font-family:var(--font-display); font-size:13px; letter-spacing:.03em; text-transform:uppercase; color:#04263a; background:linear-gradient(180deg,#7cf3ff,#25e6ff 55%,#12c8ee); box-shadow:0 0 14px rgba(37,230,255,.5),inset 0 1px 0 rgba(255,255,255,.55); transition:.16s; }} .action-row button:hover:not(:disabled) {{ filter:brightness(1.08); box-shadow:0 0 22px rgba(37,230,255,.8); }} .action-row button:disabled {{ opacity:.5; cursor:wait; }}
    .detour-field label {{ display:flex; justify-content:space-between; }} .message {{ margin-top:9px; font-size:13px; color:#cdbdf2; }} .error {{ color:#ff6b8a; text-shadow:0 0 10px rgba(255,60,90,.45); }}
    input[type=range] {{ -webkit-appearance:none; appearance:none; height:6px; padding:0; border:0; border-radius:999px; background:linear-gradient(90deg,var(--cyan),var(--pink)); box-shadow:0 0 10px rgba(255,45,149,.45); }} input[type=range]::-webkit-slider-thumb {{ -webkit-appearance:none; width:18px; height:18px; border-radius:50%; background:#fff; border:2px solid var(--pink); box-shadow:0 0 12px rgba(255,45,149,.9); cursor:pointer; }} input[type=range]::-moz-range-thumb {{ width:16px; height:16px; border-radius:50%; background:#fff; border:2px solid var(--pink); box-shadow:0 0 12px rgba(255,45,149,.9); cursor:pointer; }}
    .results-wrap {{ flex:1; min-height:0; display:flex; flex-direction:column; overflow:hidden; }} .results-head {{ flex:0 0 auto; display:flex; justify-content:space-between; gap:10px; align-items:center; padding:12px 16px 8px; border-bottom:1px solid rgba(139,92,255,.18); }} .results-head h2 {{ font-size:15px; }}
    .legend {{ color:var(--muted); font-size:10.5px; display:flex; flex-wrap:wrap; gap:10px; letter-spacing:.05em; text-transform:uppercase; }} .rare-us {{ color:var(--rare); font-weight:800; text-shadow:0 0 10px rgba(255,61,214,.5); }} .unique-state {{ font-weight:800; color:var(--gold); text-shadow:0 0 10px rgba(255,210,63,.45); }} .common-game {{ color:var(--muted); }}
    #stops {{ flex:1; min-height:0; overflow:auto; padding:0 16px 18px; }} .stop {{ border-top:1px solid rgba(139,92,255,.16); padding:12px 8px; cursor:pointer; border-radius:10px; transition:background .16s,box-shadow .16s; }} .stop:hover {{ background:rgba(37,230,255,.06); }} .stop.active {{ background:linear-gradient(180deg,rgba(255,45,149,.16),rgba(37,230,255,.10)); outline:1px solid var(--pink); outline-offset:-1px; box-shadow:0 0 18px rgba(255,45,149,.32),inset 0 0 20px rgba(37,230,255,.07); }} .stop h3 {{ margin:0 0 4px; font-size:17px; font-weight:700; color:#fff; }}
    .meta {{ color:#b6a7de; font-size:13px; }} .games {{ display:grid; grid-template-columns:repeat(auto-fit,minmax(165px,1fr)); gap:2px 14px; margin-top:8px; font-size:13px; }} .game {{ display:block; line-height:1.3; margin-bottom:4px; color:#e7ddff; }} .machine-count,.machine-kind {{ color:#9d8cc7; font-size:11px; font-weight:600; margin-left:4px; }} .machine-kind {{ white-space:nowrap; }}
    #route-map {{ height:100%; min-height:0; background:#0b0620; }} .loading {{ display:flex; align-items:center; gap:12px; color:var(--cyan); padding:18px 0; font-family:var(--font-display); font-size:13px; letter-spacing:.03em; text-transform:uppercase; text-shadow:0 0 12px rgba(37,230,255,.55); }} .car-track {{ width:78px; height:24px; position:relative; overflow:hidden; border-bottom:2px dashed rgba(255,210,63,.8); box-shadow:0 2px 10px rgba(255,210,63,.28); }} .car {{ position:absolute; left:-34px; bottom:4px; width:26px; height:10px; background:var(--pink); border-radius:7px 9px 4px 4px; box-shadow:0 0 12px rgba(255,45,149,.9); animation:drive 1.35s linear infinite; }} .car:before {{ content:""; position:absolute; left:7px; top:-6px; width:12px; height:7px; background:var(--cyan); border-radius:7px 7px 0 0; box-shadow:0 0 10px rgba(37,230,255,.8); }} .car:after {{ content:""; position:absolute; left:4px; bottom:-4px; width:4px; height:4px; background:#12002a; border-radius:50%; box-shadow:14px 0 0 #12002a; }} @keyframes drive {{ to {{ transform:translateX(112px); }} }}
    .explore-grid {{ display:grid; grid-template-columns:minmax(280px,420px) minmax(0,1fr); grid-template-rows:minmax(240px,42%) minmax(0,1fr); grid-template-areas:"controls map" "browse results"; gap:12px 18px; align-items:stretch; height:calc(100dvh - var(--topbar-height,57px) - 44px); min-height:520px; }} .explore-controls {{ grid-area:controls; align-self:start; }} .explore-map-panel {{ grid-area:map; position:relative; min-width:0; min-height:0; }} #explore-map {{ width:100%; height:100%; min-height:240px; background:#0b0620; }} #explore-results {{ grid-area:results; min-width:0; min-height:0; overflow:auto; display:grid; grid-auto-rows:max-content; align-content:start; gap:10px; padding-right:4px; }} .explore-map-empty {{ position:absolute; z-index:500; inset:auto 12px 12px; padding:8px 11px; border-radius:8px; background:rgba(10,4,26,.9); color:var(--cyan); font-size:12px; border:1px solid rgba(37,230,255,.35); box-shadow:0 0 16px rgba(37,230,255,.22); pointer-events:none; }} .searchbox {{ display:flex; gap:8px; }} .searchbox input {{ flex:1; }} .searchbox button,.browse-tree button,.mode-tabs button {{ border:0; border-radius:9px; padding:9px 13px; font-family:var(--font-display); font-size:12px; letter-spacing:.03em; text-transform:uppercase; color:#04263a; background:linear-gradient(180deg,#7cf3ff,#25e6ff 55%,#12c8ee); box-shadow:0 0 12px rgba(37,230,255,.45); transition:.16s; }} .searchbox button:hover {{ filter:brightness(1.08); box-shadow:0 0 20px rgba(37,230,255,.75); }} .mode-tabs {{ display:flex; gap:8px; margin:12px 0; }} .mode-tabs button {{ background:rgba(20,8,44,.7); color:#d7c9ff; border:1px solid var(--line); box-shadow:none; }} .mode-tabs button.active {{ background:linear-gradient(180deg,#ff6ecb,#ff2d95); color:#20002f; border-color:transparent; box-shadow:0 0 12px rgba(255,45,149,.55); }} .browse-tree {{ grid-area:browse; min-height:0; overflow:auto; display:grid; align-content:start; gap:8px; margin:0; }} .browse-tree button {{ width:100%; text-align:left; background:rgba(20,8,44,.6); color:#e7ddff; border:1px solid var(--line); display:flex; justify-content:space-between; gap:10px; box-shadow:none; font-family:var(--font-body); font-weight:600; font-size:13px; letter-spacing:0; text-transform:none; }} .browse-tree button b {{ color:var(--cyan); font-family:var(--font-body); }} .browse-tree button:hover {{ border-color:var(--cyan); color:#fff; box-shadow:0 0 12px rgba(37,230,255,.28); }} .browse-trail {{ color:var(--muted); font-size:12px; margin-top:8px; letter-spacing:.05em; text-transform:uppercase; }} .result-card {{ padding:14px; }} .result-card b {{ color:#fff; }}
    .browse-tree[hidden] {{ display:none; }}
    .leaflet-container {{ background:#0b0620; font-family:var(--font-body); }}
    .leaflet-tile-pane {{ filter:invert(1) hue-rotate(185deg) saturate(1.5) brightness(.95) contrast(.92); }}
    .leaflet-bar a {{ background:#150b2e; color:var(--cyan); border-color:rgba(139,92,255,.3); }} .leaflet-bar a:hover {{ background:#241348; color:#fff; }}
    .leaflet-popup-content-wrapper,.leaflet-popup-tip {{ background:rgba(16,7,36,.96); color:#fff; border:1px solid rgba(255,45,149,.5); border-radius:10px; box-shadow:0 0 24px rgba(255,45,149,.32); }}
    .leaflet-popup-content a {{ color:var(--cyan); }}
    .leaflet-control-attribution {{ background:rgba(10,4,26,.72)!important; color:#9d8cc7!important; }} .leaflet-control-attribution a {{ color:var(--cyan)!important; }}
    @media (max-width:900px) {{
      body.planner-active {{ overflow:auto; }}
      header {{ position:static; }} .topbar {{ align-items:flex-start; flex-direction:column; padding:12px 14px; }} .hero {{ display:block; padding:16px 14px; }} .stat-grid {{ margin-top:16px; }} main {{ padding:14px; }} .grid-2,.explore-grid {{ grid-template-columns:1fr; }} #hotspot-map {{ min-height:360px; }} .explore-grid {{ height:auto; min-height:0; grid-template-rows:auto 300px auto auto; grid-template-areas:"controls" "map" "browse" "results"; }} .browse-tree {{ max-height:none; overflow:visible; }} #explore-results {{ max-height:none; overflow:visible; padding-right:0; }}
      .planner-shell {{ grid-template-columns:1fr; grid-template-rows:auto minmax(300px,42vh) minmax(260px,1fr); height:auto; min-height:0; margin:-14px -14px -42px; }} .planner-side {{ grid-row:1 / span 3; display:contents; }} .controls {{ background:rgba(16,7,36,.94); }} #route-map {{ grid-row:2; min-height:320px; }} .results-wrap {{ grid-row:3; background:rgba(16,7,36,.94); min-height:0; display:flex; flex-direction:column; }} #stops {{ max-height:45vh; }} .trip-grid,.action-row {{ grid-template-columns:1fr; }}
    }}
    @media (prefers-reduced-motion:reduce) {{ .roadline::before,.car,.view.active {{ animation:none; }} * {{ transition-duration:.001ms!important; }} }}
  </style>
</head>
<body>
  <header>
    <div class="topbar" id="topbar"><div class="brand">Arcade Road Trip<span class="brand-sub">Atlas &mdash; neon highway to the cabinets</span></div><nav class="tabs"><button class="tab active" data-view="destinations">Destinations</button><button class="tab" data-view="planner">Plan Route</button><button class="tab" data-view="explore">Explore Games</button><button class="tab" data-view="ideas">Trip Ideas</button></nav></div>
    <div class="hero" id="hero"><div><h1>Find arcade trips worth taking.</h1><p class="lede">Scout destination cities, build road-trip stops around playable machines, and find rare games before you leave home.</p></div><div class="stat-grid"><div class="stat"><b id="total-arcades">0</b><span>active continental U.S. arcades</span></div><div class="stat"><b id="total-machines">0</b><span>known machine placements</span></div><div class="stat"><b id="total-rare">0</b><span>rare U.S. game/location hits</span></div><div class="stat"><b id="total-cities">0</b><span>cities with playable locations</span></div></div></div>
    <div class="roadline" aria-hidden="true"></div>
  </header>
  <main>
    <div class="view active" id="view-destinations">
      <section><div class="section-head"><div><h2>Continental U.S. Arcade Hotspots</h2><p class="note">Heat intensity blends arcade density and machine count.</p></div></div><div class="panel"><div id="hotspot-map"></div></div></section>
      <section><div class="section-head"><div><h2>Top 25 Arcade Destination Cities</h2><p class="note">Sort by arcade count, total machines, or rare U.S. machines.</p></div><div class="sorter" data-target="city-table"><button data-sort="arcades" class="active">Arcades</button><button data-sort="machines">Machines</button><button data-sort="rare_us_machines">Rare U.S.</button></div></div><div class="panel table-wrap"><table id="city-table"></table></div></section>
      <section class="grid-2"><div><div class="section-head"><div><h2>Top 25 States</h2><p class="note">Lower 48 plus D.C.</p></div><div class="sorter" data-target="state-table"><button data-sort="arcades" class="active">Arcades</button><button data-sort="machines">Machines</button><button data-sort="rare_us_machines">Rare U.S.</button></div></div><div class="panel table-wrap"><table id="state-table"></table></div></div><div><div class="section-head"><div><h2>Machines Per Arcade Distribution</h2><p class="note">The long tail of large museums, halls, and mega-arcades carries a lot of inventory.</p></div></div><div class="panel panel-pad"><svg id="machine-distribution" viewBox="0 0 760 560"></svg></div></div></section>
      <section><div class="section-head"><div><h2>Largest 25 Individual Arcades</h2><p class="note">Sort by total known machines or rare U.S. games.</p></div><div class="sorter" data-target="arcade-table"><button data-sort="machines" class="active">Machines</button><button data-sort="rare_us_machines">Rare U.S.</button></div></div><div class="panel table-wrap"><table id="arcade-table"></table></div></section>
    </div>
    <div class="view" id="view-planner"><div class="planner-shell"><aside class="planner-side"><div class="controls"><div class="trip-grid"><div><label>Origin</label><input id="origin" value="South Jordan, UT" /></div><div><label>Destination</label><input id="destination" value="Ogden, UT" /></div></div><div class="action-row"><div class="detour-field"><label><span>Max detour</span><span><span id="detourLabel">15</span> mi</span></label><input id="detour" type="range" min="2" max="60" value="15" /></div><button id="plan" disabled>Loading data...</button></div><div id="status" class="message"></div><div id="message" class="message error"></div></div><div class="results-wrap"><div class="results-head"><h2>Arcades:</h2><div class="legend"><span class="rare-us">Under 10 in U.S.</span><span class="unique-state">Only one in state</span><span class="common-game">more common</span></div></div><div id="stops"></div></div></aside><div id="route-map"></div></div></div>
    <div class="view" id="view-explore"><section class="explore-grid"><div class="panel panel-pad explore-controls"><h2>Explore Games</h2><p class="note">Search for a title or browse the playable catalog by game type and maker.</p><div class="mode-tabs"><button class="active" data-explore-mode="search">Search</button><button id="browse-games" data-explore-mode="browse" disabled>Browse</button></div><div id="explore-search-panel"><div class="searchbox"><input id="game-search" value="Godzilla" /><button id="search-games" disabled>Search</button></div></div><div id="explore-browse-panel" hidden><div class="browse-trail" id="browse-trail">All Games</div></div><div id="explore-message" class="message"></div></div><div class="panel explore-map-panel"><div id="explore-map" aria-label="Map of matching arcade locations"></div><div id="explore-map-empty" class="explore-map-empty">Search for a game to map its locations.</div></div><div id="browse-tree" class="panel panel-pad browse-tree" hidden></div><div id="explore-results"></div></section></div>
    <div class="view" id="view-ideas"><section class="grid-2"><div class="panel panel-pad"><h2>Plan A Better Detour</h2><p>Start with a route, set how far you are willing to wander, and let the atlas surface stops with deep game lists, unusual cabinets, and dense local clusters.</p><p class="note">Map pins and result cards stay linked so you can jump between the route and the arcade list while tuning the trip.</p></div><div class="panel panel-pad"><h2>Hunt For Specific Games</h2><p>Use search when you know the title. Use Browse when you want to wander the catalog by pinball, arcade, and manufacturer.</p><p class="note">Rare-game markers highlight machines found in fewer than ten known U.S. locations.</p></div></section><section class="panel panel-pad"><h2>Snapshot</h2><p id="snapshot-counts" class="note"></p><p class="note">Generated {generated}. Counts reflect active continental U.S. locations in the current snapshot.</p></section></div>
  </main>
  <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>
  <script src="https://unpkg.com/leaflet.heat@0.2.0/dist/leaflet-heat.js"></script>
  <script type="module">
import * as duckdb from 'https://cdn.jsdelivr.net/npm/@duckdb/duckdb-wasm/+esm';
const DATA={dashboard_payload};
const EMBEDDED_PARQUET={parquet_payload};
const format=new Intl.NumberFormat(); const $=id=>document.getElementById(id);
let conn, hotspotMap, routeMap, routeLayer, exploreMap, exploreMarkers, markers=[], markerByLocationId=new Map();
function esc(v){{return String(v??'').replace(/[&<>"']/g,ch=>({{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}}[ch]));}}
function mapsSearchQuery(r){{const name=r.name||r.location_name||r.label||''; return [name,r.street_address,r.city,r.state].filter(Boolean).join(' ');}}
function arcadeUrl(r){{const site=String(r.website_url||'').trim(); if(site)return /^https?:\\/\\//i.test(site)?site:`https://${{site}}`; const query=mapsSearchQuery(r)||String(r.name||r.location_name||r.label||'arcade'); const place=String(r.google_place_id||'').trim(); if(place)return `https://www.google.com/maps/search/?api=1&query=${{encodeURIComponent(query)}}&query_place_id=${{encodeURIComponent(place)}}`; return `https://www.google.com/maps/search/?api=1&query=${{encodeURIComponent(query)}}`;}}
function arcadeNameLink(r,label){{return `<a class="arcade-link" href="${{esc(arcadeUrl(r))}}" target="_blank" rel="noopener noreferrer">${{esc(label??r.name??r.location_name??r.label??'')}}</a>`;}}
function rowObjects(r){{return r.toArray().map(row=>row.toJSON?row.toJSON():Object.fromEntries(row));}}
function base64ToBytes(v){{const b=atob(v), bytes=new Uint8Array(b.length); for(let i=0;i<b.length;i++)bytes[i]=b.charCodeAt(i); return bytes;}}
function topRows(rows,metric,limit=25){{return [...rows].sort((a,b)=>(b[metric]||0)-(a[metric]||0)||String(a.label||a.name).localeCompare(String(b.label||b.name))).slice(0,limit);}}
function bar(value,max){{const pct=max?Math.max(2,Math.round(value/max*100)):0; return `<div class="bar"><span style="width:${{pct}}%"></span><b>${{format.format(value||0)}}</b></div>`;}}
function renderRankTable(id,rows,metric,cols){{const selected=topRows(rows,metric), max=Math.max(...selected.map(r=>r[metric]||0),1); $(id).innerHTML=`<thead><tr><th>Rank</th>${{cols.map(c=>`<th data-sort="${{c.key}}">${{c.label}}</th>`).join('')}}</tr></thead><tbody>${{selected.map((r,i)=>`<tr><td>${{i+1}}</td>${{cols.map(c=>{{const v=r[c.key]||0;if(c.kind==='name'){{const nameHtml=c.link?arcadeNameLink(r,r[c.key]||''):esc(r[c.key]||'');return `<td class="name">${{nameHtml}}${{r.sub?`<div class="small">${{esc(r.sub)}}</div>`:''}}</td>`;}}if(c.kind==='bar')return `<td class="bar-cell">${{bar(v,max)}}</td>`;if(c.kind==='rare')return `<td class="rare">${{format.format(v)}}</td>`;return `<td>${{format.format(v)}}</td>`;}}).join('')}}</tr>`).join('')}}</tbody>`;}}
const tableConfigs={{'city-table':{{rows:DATA.cities,sort:'arcades',columns:[{{key:'label',label:'City',kind:'name'}},{{key:'arcades',label:'Arcades',kind:'bar'}},{{key:'machines',label:'Machines'}},{{key:'rare_us_machines',label:'Rare U.S.',kind:'rare'}}]}},'state-table':{{rows:DATA.states,sort:'arcades',columns:[{{key:'label',label:'State',kind:'name'}},{{key:'arcades',label:'Arcades',kind:'bar'}},{{key:'machines',label:'Machines'}},{{key:'rare_us_machines',label:'Rare U.S.',kind:'rare'}}]}},'arcade-table':{{rows:DATA.arcades.map(r=>({{...r,label:r.name,sub:[r.city,r.state].filter(Boolean).join(', ')+(r.street_address?' - '+r.street_address:'')}})),sort:'machines',columns:[{{key:'label',label:'Arcade',kind:'name',link:true}},{{key:'machines',label:'Machines',kind:'bar'}},{{key:'unique_games',label:'Unique Games'}},{{key:'rare_us_machines',label:'Rare U.S.',kind:'rare'}},{{key:'pinball_machines',label:'Pinball'}}]}}}};
function setSort(id,metric){{const c=tableConfigs[id]; c.sort=metric; document.querySelectorAll(`.sorter[data-target="${{id}}"] button`).forEach(b=>b.classList.toggle('active',b.dataset.sort===metric)); renderRankTable(id,c.rows,metric,c.columns);}}
function initDashboard(){{$('total-arcades').textContent=format.format(DATA.totals.arcades);$('total-machines').textContent=format.format(DATA.totals.machines);$('total-rare').textContent=format.format(DATA.totals.rare_us_machines);$('total-cities').textContent=format.format(DATA.totals.cities); Object.entries(tableConfigs).forEach(([id,c])=>renderRankTable(id,c.rows,c.sort,c.columns)); document.querySelectorAll('.sorter button').forEach(b=>b.addEventListener('click',()=>setSort(b.closest('.sorter').dataset.target,b.dataset.sort))); hotspotMap=L.map('hotspot-map',{{scrollWheelZoom:false}}).setView([39.5,-98.35],4); L.tileLayer('https://tile.openstreetmap.org/{{z}}/{{x}}/{{y}}.png',{{maxZoom:18,attribution:'&copy; OpenStreetMap contributors'}}).addTo(hotspotMap); const max=Math.max(...DATA.heat_points.map(p=>p.machines),1); L.heatLayer(DATA.heat_points.map(p=>[p.lat,p.lon,.18+.82*Math.sqrt(p.machines/max)]),{{radius:13,blur:8,maxZoom:8,gradient:{{.15:'#25e6ff',.45:'#8b5cff',.72:'#ff2d95',1:'#ffe600'}}}}).addTo(hotspotMap); renderMachineDistribution();}}
function renderMachineDistribution(){{const svg=$('machine-distribution'), rows=DATA.machine_distribution, width=760,height=560,pad={{left:64,right:28,top:34,bottom:56}},pw=width-pad.left-pad.right,ph=height-pad.top-pad.bottom,maxA=Math.max(...rows.map(r=>r.arcades),1),maxM=Math.max(...rows.map(r=>r.machines),1),gap=12,bw=(pw-gap*(rows.length-1))/rows.length; const bars=rows.map((r,i)=>{{const x=pad.left+i*(bw+gap),h=ph*r.arcades/maxA,y=pad.top+ph-h,rareRatio=r.machines?r.rare_us_machines/r.machines:0,fill=rareRatio>.18?'#ff2d95':rareRatio>.08?'#ffd23f':'#25e6ff'; return `<g><rect x="${{x}}" y="${{y}}" width="${{bw}}" height="${{h}}" rx="5" fill="${{fill}}" opacity=".86"></rect><text x="${{x+bw/2}}" y="${{height-31}}" text-anchor="middle" font-size="12" fill="#c3b2ee">${{r.label}}</text><text x="${{x+bw/2}}" y="${{y-8}}" text-anchor="middle" font-size="12" font-weight="800" fill="#fff">${{format.format(r.arcades)}}</text></g>`;}}).join(''); const line=rows.map((r,i)=>{{const x=pad.left+i*(bw+gap)+bw/2,y=pad.top+ph-ph*r.machines/maxM;return `${{i?'L':'M'}} ${{x}} ${{y}}`;}}).join(' '); const dots=rows.map((r,i)=>{{const x=pad.left+i*(bw+gap)+bw/2,y=pad.top+ph-ph*r.machines/maxM;return `<circle cx="${{x}}" cy="${{y}}" r="4" fill="#59ff9c"></circle>`;}}).join(''); svg.innerHTML=`<line x1="${{pad.left}}" y1="${{pad.top+ph}}" x2="${{width-pad.right}}" y2="${{pad.top+ph}}" stroke="rgba(139,92,255,.45)"/><line x1="${{pad.left}}" y1="${{pad.top}}" x2="${{pad.left}}" y2="${{pad.top+ph}}" stroke="rgba(139,92,255,.45)"/><text x="18" y="${{pad.top+ph/2}}" transform="rotate(-90 18 ${{pad.top+ph/2}})" text-anchor="middle" font-size="12" fill="#b3a4d6">Arcade count</text><text x="${{width/2}}" y="${{height-10}}" text-anchor="middle" font-size="12" fill="#b3a4d6">Known machines at one arcade</text>${{bars}}<path d="${{line}}" fill="none" stroke="#59ff9c" stroke-width="2.5" stroke-linejoin="round"/>${{dots}}<text x="${{width-180}}" y="34" font-size="12" font-weight="800" fill="#59ff9c">lime line = total machines in bin</text>`;}}
async function bootDuckDB(){{$('status').textContent='Loading embedded arcade data...'; const bundle=await duckdb.selectBundle(duckdb.getJsDelivrBundles()); const workerUrl=URL.createObjectURL(new Blob([`importScripts("${{bundle.mainWorker}}");`],{{type:'text/javascript'}})); const worker=new Worker(workerUrl); const db=new duckdb.AsyncDuckDB(new duckdb.ConsoleLogger(),worker); await db.instantiate(bundle.mainModule,bundle.pthreadWorker); URL.revokeObjectURL(workerUrl); await db.registerFileBuffer('route_locations.parquet',base64ToBytes(EMBEDDED_PARQUET.route_locations)); await db.registerFileBuffer('location_games.parquet',base64ToBytes(EMBEDDED_PARQUET.location_games)); conn=await db.connect(); await conn.query("CREATE VIEW route_locations AS SELECT * FROM read_parquet('route_locations.parquet')"); await conn.query("CREATE VIEW location_games AS SELECT * FROM read_parquet('location_games.parquet')"); $('status').textContent=`Loaded ${{EMBEDDED_PARQUET.manifest.counts.route_locations.toLocaleString()}} arcades and ${{EMBEDDED_PARQUET.manifest.counts.location_games.toLocaleString()}} machine placements.`; $('snapshot-counts').textContent=$('status').textContent; $('plan').disabled=false; $('plan').textContent='Plan trip'; $('search-games').disabled=false; $('browse-games').disabled=false; renderBrowseRoot();}}
function initRouteMap(){{if(routeMap)return; routeMap=L.map('route-map',{{maxBounds:L.latLngBounds([24.396308,-124.848974],[49.384358,-66.885444]),maxBoundsViscosity:1,minZoom:4}}).setView([39.5,-98.35],4); L.tileLayer('https://tile.openstreetmap.org/{{z}}/{{x}}/{{y}}.png',{{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}}).addTo(routeMap);}}
function initExploreMap(){{if(exploreMap)return; exploreMap=L.map('explore-map',{{zoomControl:false,attributionControl:true,dragging:false,touchZoom:false,scrollWheelZoom:false,doubleClickZoom:false,boxZoom:false,keyboard:false}}).setView([39.5,-98.35],4); L.tileLayer('https://tile.openstreetmap.org/{{z}}/{{x}}/{{y}}.png',{{maxZoom:10,attribution:'&copy; OpenStreetMap contributors'}}).addTo(exploreMap); exploreMarkers=L.layerGroup().addTo(exploreMap);}}
function renderExploreMap(rows){{initExploreMap(); exploreMarkers.clearLayers(); const seen=new Set(), points=[]; for(const r of rows){{const lat=Number(r.latitude),lon=Number(r.longitude),key=`${{lat}},${{lon}}`; if(!Number.isFinite(lat)||!Number.isFinite(lon)||seen.has(key))continue; seen.add(key); points.push([lat,lon]); L.circleMarker([lat,lon],{{radius:6,color:'#0b0620',weight:2,fillColor:'#25e6ff',fillOpacity:.95,interactive:false}}).addTo(exploreMarkers);}} $('explore-map-empty').style.display=points.length?'none':'block'; if(points.length)exploreMap.fitBounds(L.latLngBounds(points),{{padding:[28,28],maxZoom:6,animate:false}}); else exploreMap.setView([39.5,-98.35],4,{{animate:false}});}}
function parsePoint(t){{const p=t.split(',').map(v=>Number(v.trim())); return p.length===2&&p.every(Number.isFinite)?{{lat:p[0],lon:p[1]}}:null;}} async function geocode(t,label){{t=t.trim(); if(!t)throw new Error(`Enter a ${{label}}.`); const p=parsePoint(t); if(p)return p; const r=await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&countrycodes=us&q=${{encodeURIComponent(t)}}`), d=await r.json(); if(!r.ok||!d?.length)throw new Error(`Could not geocode: ${{t}}`); return {{lat:Number(d[0].lat),lon:Number(d[0].lon)}};}}
async function routeBetween(o,d){{const r=await fetch(`https://router.project-osrm.org/route/v1/driving/${{o.lon}},${{o.lat}};${{d.lon}},${{d.lat}}?overview=full&geometries=geojson&steps=false`), data=await r.json(); if(!r.ok||!data.routes?.length)throw new Error('No route found.'); return data.routes[0];}}
function hav(a,b){{const R=3958.7613,p1=a.lat*Math.PI/180,p2=b.lat*Math.PI/180,dp=(b.lat-a.lat)*Math.PI/180,dl=(b.lon-a.lon)*Math.PI/180,h=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return R*2*Math.atan2(Math.sqrt(h),Math.sqrt(1-h));}} function proj(p,pts){{let best=Infinity,stride=Math.max(1,Math.floor(pts.length/650)); for(let i=0;i<pts.length;i+=stride)best=Math.min(best,hav(p,pts[i])); return best;}} function bounds(pts,m){{const la=pts.map(p=>p.lat),lo=pts.map(p=>p.lon),minLat=Math.min(...la),maxLat=Math.max(...la),minLon=Math.min(...lo),maxLon=Math.max(...lo),latPad=m/69,mid=(minLat+maxLat)/2,lonPad=m/Math.max(20,69*Math.cos(mid*Math.PI/180)); return {{minLat:minLat-latPad,maxLat:maxLat+latPad,minLon:minLon-lonPad,maxLon:maxLon+lonPad}};}}
async function candidates(b){{return rowObjects(await conn.query(`SELECT * FROM route_locations WHERE latitude BETWEEN ${{Number(b.minLat)}} AND ${{Number(b.maxLat)}} AND longitude BETWEEN ${{Number(b.minLon)}} AND ${{Number(b.maxLon)}} ORDER BY game_count DESC LIMIT 2000`));}} async function gamesFor(ids){{if(!ids.length)return new Map(); const rows=rowObjects(await conn.query(`SELECT * FROM location_games WHERE location_id IN (${{ids.map(Number).filter(Number.isFinite).join(',')}}) ORDER BY rare_us DESC, unique_state DESC, cabinet_type, name`)), g=new Map(); for(const r of rows){{if(!g.has(r.location_id))g.set(r.location_id,[]); g.get(r.location_id).push(r);}} return g;}}
function machineKind(r){{return String(r.cabinet_type||r.machine_kind||'').toLowerCase()==='pinball'?'pinball':'video';}}
function machineKindLabel(r){{return machineKind(r)==='pinball'?'⚪ Pinball':'🕹️ Video';}}
function machineKindBadge(r){{return `<span class="machine-kind">${{machineKindLabel(r)}}</span>`;}}
function renderGames(gs){{return gs.map(g=>{{let name=esc(g.name), content=name; if(Number(g.rare_us))content=`<strong class="rare-us">${{name}}<span class="machine-count">(${{g.us_location_count}} US)</span></strong>`; else if(Number(g.unique_state))content=`<strong class="unique-state">${{name}}</strong>`; return `<span class="game">${{content}} ${{machineKindBadge(g)}}</span>`;}}).join('');}}
function selectStop(id,opt={{}}){{document.querySelectorAll('.stop.active').forEach(e=>e.classList.remove('active')); const card=document.querySelector(`.stop[data-location-id="${{id}}"]`); if(card){{card.classList.add('active'); if(opt.scroll!==false)card.scrollIntoView({{block:'nearest',behavior:'smooth'}});}} const marker=markerByLocationId.get(Number(id)); if(marker){{marker.openPopup(); if(opt.pan!==false)routeMap.panTo(marker.getLatLng(),{{animate:true}});}}}}
async function planTrip(){{initRouteMap(); $('message').textContent=''; $('stops').innerHTML='<div class="loading"><span>Planning your trip...</span><span class="car-track"><span class="car"></span></span></div>'; $('plan').disabled=true; $('plan').textContent='Planning...'; try{{const o=await geocode($('origin').value,'starting point'), d=await geocode($('destination').value,'destination'), route=await routeBetween(o,d), pts=route.geometry.coordinates.map(([lon,lat])=>({{lat,lon}})), max=Number($('detour').value), cand=await candidates(bounds(pts,max)); const stops=cand.map(l=>{{const rd=proj({{lat:Number(l.latitude),lon:Number(l.longitude)}},pts), det=rd*2, bonus=l.source_tags?10:0; return {{...l,estimated_detour_miles:det,score:Number(l.game_count||0)*1.5+Number(l.pinball_games||0)*.6+Number(l.rhythm_games||0)*2+bonus-det*2.5}};}}).filter(l=>l.estimated_detour_miles<=max).sort((a,b)=>b.score-a.score).slice(0,25), games=await gamesFor(stops.map(s=>s.location_id)); if(routeLayer)routeMap.removeLayer(routeLayer); markers.forEach(m=>routeMap.removeLayer(m)); markers=[]; markerByLocationId=new Map(); routeLayer=L.geoJSON(route.geometry,{{style:{{color:'#ff2d95',weight:6}}}}).addTo(routeMap); routeMap.fitBounds(routeLayer.getBounds(),{{padding:[24,24],maxZoom:12}}); stops.forEach(s=>{{const m=L.marker([s.latitude,s.longitude]).addTo(routeMap).bindPopup(`<b>${{arcadeNameLink(s)}}</b><br>${{esc(s.city)}}, ${{esc(s.state)}}<br>${{s.estimated_detour_miles.toFixed(2)}} mi detour`); m.on('click',()=>selectStop(s.location_id,{{pan:false}})); markers.push(m); markerByLocationId.set(Number(s.location_id),m);}}); $('stops').innerHTML=stops.map(s=>`<section class="stop" data-location-id="${{s.location_id}}" tabindex="0"><h3>${{arcadeNameLink(s)}}</h3><div class="meta">${{esc(s.city)}}, ${{esc(s.state)}} · ${{format.format(s.game_count||0)}} games · ${{s.estimated_detour_miles.toFixed(2)}} mi estimated detour · ${{esc(s.source_tags||'local')}}</div><div class="games">${{renderGames(games.get(s.location_id)||[])}}</div></section>`).join('')||'<p>No stops inside this detour budget.</p>'; document.querySelectorAll('.stop').forEach(c=>c.addEventListener('click',e=>{{if(e.target.closest('a'))return; selectStop(c.dataset.locationId);}}));}}catch(e){{$('message').textContent=e.message;$('stops').innerHTML='';}}finally{{$('plan').disabled=false;$('plan').textContent='Plan trip';}}}}
function renderGameLocations(rows){{return rows.map(r=>`<div class="panel result-card"><b>${{esc(r.canonical_name)}}</b> ${{machineKindBadge(r)}} <span class="small">${{r.us_location_count}} U.S. locations</span><div>${{arcadeNameLink(r,r.location_name)}} · ${{esc(r.city)}}, ${{esc(r.state)}}</div><div class="small">${{esc(r.street_address)}} · ${{format.format(r.game_count||0)}} known machines</div></div>`).join('')||'<p>No matches.</p>';}}
async function searchGames(){{const q=$('game-search').value.trim().replaceAll("'","''"); if(!q)return; $('explore-message').textContent='Searching...'; const rows=rowObjects(await conn.query(`SELECT lg.canonical_name, lg.cabinet_type, lg.us_location_count, lg.state_location_count, lg.rare_us, rl.name AS location_name, rl.city, rl.state, rl.street_address, rl.website_url, rl.google_place_id, rl.google_cid, rl.game_count, rl.latitude, rl.longitude FROM location_games lg JOIN route_locations rl USING(location_id) WHERE lower(lg.name) LIKE lower('%${{q}}%') OR lower(lg.canonical_name) LIKE lower('%${{q}}%') ORDER BY lg.us_location_count ASC, rl.game_count DESC LIMIT 80`)); $('explore-message').textContent=`${{rows.length}} matching location rows`; $('explore-results').innerHTML=renderGameLocations(rows); renderExploreMap(rows);}}
function gameKindSql(kind){{return kind==='pinball'?"lower(cabinet_type) = 'pinball'":"lower(cabinet_type) <> 'pinball'";}}
async function renderBrowseRoot(){{$('browse-trail').textContent='All Games'; $('explore-message').textContent=''; $('browse-tree').innerHTML='<button data-kind="pinball"><span>⚪ Pinball</span><b>...</b></button><button data-kind="arcade"><span>🕹️ Video</span><b>...</b></button>'; const rows=rowObjects(await conn.query(`SELECT CASE WHEN lower(cabinet_type) = 'pinball' THEN 'pinball' ELSE 'arcade' END AS kind, COUNT(DISTINCT canonical_game_id) AS games FROM location_games GROUP BY 1`)); const counts=Object.fromEntries(rows.map(r=>[r.kind,r.games])); $('browse-tree').innerHTML=['pinball','arcade'].map(kind=>`<button data-kind="${{kind}}"><span>${{kind==='pinball'?'⚪ Pinball':'🕹️ Video'}}</span><b>${{format.format(counts[kind]||0)}}</b></button>`).join(''); document.querySelectorAll('[data-kind]').forEach(b=>b.addEventListener('click',()=>renderBrowseManufacturers(b.dataset.kind)));}}
async function renderBrowseManufacturers(kind){{$('browse-trail').textContent=`All Games / ${{kind==='pinball'?'⚪ Pinball':'🕹️ Video'}}`; $('explore-results').innerHTML=''; $('explore-message').textContent='Loading makers...'; const rows=rowObjects(await conn.query(`SELECT COALESCE(NULLIF(manufacturer,''),'Unknown') AS manufacturer, COUNT(DISTINCT canonical_game_id) AS games, SUM(rare_us) AS rare_hits FROM location_games WHERE ${{gameKindSql(kind)}} GROUP BY 1 ORDER BY games DESC, manufacturer LIMIT 80`)); $('explore-message').textContent=`${{rows.length}} makers`; $('browse-tree').innerHTML=`<button data-root="1"><span>All Games</span><b>Back</b></button>`+rows.map(r=>`<button data-kind="${{kind}}" data-maker="${{esc(r.manufacturer)}}"><span>${{esc(r.manufacturer)}}</span><b>${{format.format(r.games)}}</b></button>`).join(''); document.querySelector('[data-root]').addEventListener('click',renderBrowseRoot); document.querySelectorAll('[data-maker]').forEach(b=>b.addEventListener('click',()=>renderBrowseGames(b.dataset.kind,b.dataset.maker)));}}
async function renderBrowseGames(kind,maker){{const safeMaker=maker.replaceAll("'","''"); $('browse-trail').textContent=`All Games / ${{kind==='pinball'?'⚪ Pinball':'🕹️ Video'}} / ${{maker}}`; $('explore-results').innerHTML=''; $('explore-message').textContent='Loading games...'; const rows=rowObjects(await conn.query(`SELECT canonical_name, CASE WHEN lower(MIN(cabinet_type)) = 'pinball' THEN 'pinball' ELSE 'video' END AS machine_kind, MIN(us_location_count) AS us_location_count, COUNT(DISTINCT location_id) AS listed_locations, MAX(rare_us) AS rare_us FROM location_games WHERE ${{gameKindSql(kind)}} AND COALESCE(NULLIF(manufacturer,''),'Unknown') = '${{safeMaker}}' GROUP BY canonical_game_id, canonical_name ORDER BY us_location_count ASC, canonical_name LIMIT 120`)); $('explore-message').textContent=`${{rows.length}} games`; $('browse-tree').innerHTML=`<button data-kind="${{kind}}"><span>${{kind==='pinball'?'⚪ Pinball':'🕹️ Video'}} makers</span><b>Back</b></button>`+rows.map(r=>`<button data-game="${{esc(r.canonical_name)}}"><span>${{machineKindLabel(r)}} · ${{esc(r.canonical_name)}}</span><b>${{format.format(r.us_location_count)}} US</b></button>`).join(''); document.querySelector('[data-kind]').addEventListener('click',()=>renderBrowseManufacturers(kind)); document.querySelectorAll('[data-game]').forEach(b=>b.addEventListener('click',()=>showBrowseGame(b.dataset.game)));}}
async function showBrowseGame(game){{const safeGame=game.replaceAll("'","''"); $('explore-message').textContent='Loading locations...'; const rows=rowObjects(await conn.query(`SELECT lg.canonical_name, lg.cabinet_type, lg.us_location_count, lg.state_location_count, lg.rare_us, rl.name AS location_name, rl.city, rl.state, rl.street_address, rl.website_url, rl.google_place_id, rl.google_cid, rl.game_count, rl.latitude, rl.longitude FROM location_games lg JOIN route_locations rl USING(location_id) WHERE lg.canonical_name = '${{safeGame}}' ORDER BY rl.state, rl.city, rl.name LIMIT 120`)); $('explore-message').textContent=`${{rows.length}} playable locations shown`; $('explore-results').innerHTML=renderGameLocations(rows); renderExploreMap(rows);}}
function setExploreMode(mode){{document.querySelectorAll('[data-explore-mode]').forEach(b=>b.classList.toggle('active',b.dataset.exploreMode===mode)); $('explore-search-panel').hidden=mode!=='search'; $('explore-browse-panel').hidden=mode!=='browse'; $('browse-tree').hidden=mode!=='browse'; $('explore-results').innerHTML=''; $('explore-message').textContent=''; renderExploreMap([]); if(mode==='browse'&&conn)renderBrowseRoot();}}
function activateView(name){{document.documentElement.style.setProperty('--topbar-height',`${{$('topbar').offsetHeight}}px`); document.body.classList.toggle('planner-active',name==='planner'); document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.view===name)); document.querySelectorAll('.view').forEach(v=>v.classList.remove('active')); $('view-'+name).classList.add('active'); $('hero').style.display=name==='destinations'?'':'none'; if(name==='planner')setTimeout(()=>{{initRouteMap();routeMap.invalidateSize();}},50); if(name==='explore')setTimeout(()=>{{initExploreMap();exploreMap.invalidateSize();}},50); if(name==='destinations'&&hotspotMap)setTimeout(()=>hotspotMap.invalidateSize(),50);}}
document.querySelectorAll('.tab').forEach(t=>t.addEventListener('click',()=>activateView(t.dataset.view)));
window.addEventListener('resize',()=>document.documentElement.style.setProperty('--topbar-height',`${{$('topbar').offsetHeight}}px`));
$('detour').addEventListener('input',()=>$('detourLabel').textContent=$('detour').value); $('plan').addEventListener('click',planTrip); $('search-games').addEventListener('click',searchGames); $('game-search').addEventListener('keydown',e=>{{if(e.key==='Enter')searchGames();}}); document.querySelectorAll('[data-explore-mode]').forEach(b=>b.addEventListener('click',()=>setExploreMode(b.dataset.exploreMode)));
activateView('destinations');
initDashboard(); bootDuckDB().catch(e=>{{$('message').textContent='Could not load embedded DuckDB data: '+e.message; $('explore-message').textContent=e.message;}});
  </script>
</body>
</html>"""


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generate one-file static Arcade Road Trip app.")
    parser.add_argument("--db", type=Path, default=DEFAULT_DB)
    parser.add_argument("--data-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    return parser


def main() -> int:
    args = build_parser().parse_args()
    counts = ensure_parquet(args.db, args.data_dir)
    with dashboard_connect(args.db) as conn:
        dashboard = build_dashboard_data(conn)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(build_html(dashboard, embedded_parquet(args.data_dir, counts)))
    print(f"wrote {args.output}")
    print(f"embedded {counts['route_locations']} locations and {counts['location_games']} game placements")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
